### ISSUE TITLE
Client app port is not exposed in the Docker Compose configuration

### ISSUE THREAD

**Issue by aminnairi** [aminnairi/kryptonian#150]
**Describe the bug**
The client application used for testing this library is exposed at port `5173`, which is not forwarded by the Docker Compose configuration.

**To Reproduce**
1. Use Docker for starting the watchers for the main, shared, server & client packages 
2. Try to access the client application from a browser
3. See that the client application is not accessible

**Expected behavior**
The client application should be accessible from the container.

**Screenshots**
None.

**Environment (please complete the following information):**
 - OS [e.g. Windows 10]: Archlinux
 - Node version [e.g 20.2.1]: 20.0.0
 - NPM version [e.g 8.4.7]: 9.6.4
 - Package version [e.g. 0.1.0]: 4.0.0

**Additional context**
This is caused by a mistake in the `docker-compose.yaml` configuration which has no definition for the `ports` property. A quick fix is either to update the `docker-compose.yaml` file directly.

```yaml
---
version: "3"

services:
  node:
    image: node:20.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    env_file: .env
    ports:
      - 5173:5173
      - 8000:8000
    volumes:
      - .:/home/node
```

Or to use a Docker Compose override file.

```bash
touch docker-compose.override.yaml
```

```yaml
---
version: "3"

services:
  node:
    ports:
      - 5173:5173
      - 8000:8000
```

Finally, you will also need to tell Vite to listen to every IP addresses in order for the Docker Compose port forwarding to take effect.

```typescript
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [
    react(),
  ],
  server: {
    port: 5173,
    host: "0.0.0.0"
  }
});
```

These changes will require a full restart of the services.

```bash
docker compose down --remove-orphans --volumes --timeout 0
docker compose up --detach
```
